version: '3'

services:
  thumbor:
    image: apsl/thumbor
    volumes:
      - .:/app
      - ./images:/images
      - ./cache:/cache
      - ./thumbor.conf:/etc/thumbor.conf
    ports:
      - "8181:8000"