apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbor
  labels:
    app: thumbor
spec:
  selector:
    matchLabels:
      app: thumbor
  template:
    metadata:
      labels:
        app: thumbor
    spec:
      containers:
      - name: thumbor
        image: apsl/thumbor
        args:
          - /docker-entrypoint.sh
        ports:
          - containerPort: 8000
            name: http
        volumeMounts:
          - mountPath: /images
            name: app-data
        # - mountPath: /etc/thumbor.conf
        #   name: conf-etc-volume
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: thumbor-pvc
        # - name: conf-etc-volume
        #   configMap:
        #     name: thumbor-conf
